wifi-info:
  base-url:
    "http://openapi.seoul.go.kr:8088"
  path:
    "json/TbPublicWifiInfo"
  token:
    "4b4e6452486e6d6e37394a45494f65"


#https://devlog-wjdrbs96.tistory.com/199
#위와 같이 view 이름 predix, suffix에 붙는 것들을 설정할 수 있다.
# prefix는 앞에 폴더의 경로이고 suffix는 확장자
# 컨트롤러에서 string 리턴할 경우 prefix의 경로가 붙고 뒤에는 suffix가 붙어서 jsp 페이지를 연결하게 된다.
# 보통 jsp는 안 쓰고 Thymeleaf 사용
# @RestController는 html을 사용. jsp를 파싱할때는 @Controller로 바꿔줘야한다.
# 뷰생성 https://shallow-learning.tistory.com/entry/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8-6-Spring-MVC-View-%EB%A7%8C%EB%93%A4%EA%B8%B0-JSP%EC%99%80-Thymeleaf
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12345678
  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
